spring:
  application:
    name: Xzao
  datasource:
    url: jdbc:postgresql://localhost:5432/xzao
    username: postgres
    password: AL442218sta
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  web:
    resources:
      static-locations: classpath:/static/

logging:
  level:
    org.springframework.security: DEBUG
