spring:
  application:
    name: Xzao
  datasource:
    url: jdbc:postgresql://localhost:5432/xzao
    username: postgres
    password: AL442218sta
    data: classpath:data.sql
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
